# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7f1534a8e397af903e296eb7037360d41174b2540690a60d9f9628c096369f4691b139bc7e928e295b91fa7f7bdb975b08b8c673d76e565d90dc048e9dc06bf

test:
  secret_key_base: 52b6a798f71612f294c583fbe95af7a0de9a9281cb4ae4a7ced2c1f1ed89fda86ebaf9a8d1f7569278619204461739ab7c376f7f52e8ec40bf39a91c2c0bbaa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
